version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: patients-backend
    environment:
      - NODE_ENV=production
      - DB_FILE=/app/data/patients.sqlite3
    volumes:
      - backend_data:/app/data
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: patients-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  backend_data:
